name: Code Review

on:
  pull_request:

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get diff
        id: diff
        run: |
          git fetch origin ${{ github.base_ref }}
          DIFF=$(git diff origin/${{ github.base_ref }} HEAD)
          echo "diff<<EOF" >> $GITHUB_OUTPUT
          echo "$DIFF" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Call Code Review API
        id: review
        uses: actions/github-script@v6
        env:
          GIT_DIFF: "${{ steps.diff.outputs.diff }}"
        with:
          script: |
            const diff = process.env.GIT_DIFF;
            const response = await fetch('https://companion-away-works-wellington.trycloudflare.com/review', {
              method: 'POST',
              headers: {
                'Content-Type': 'application/json'
              },
              body: JSON.stringify({ diff })
            });
            const { comments } = await response.json();
            console.log('Comments from API:', comments);
            return JSON.stringify(comments);
          
      - name: Create review with inline comments
        uses: actions/github-script@v6
        env:
          INLINE_COMMENTS: "${{ steps.review.outputs.result }}"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const comments = JSON.parse(process.env.INLINE_COMMENTS || '[]');
            if (comments.length === 0) {
              console.log('No inline comments generated.');
              return;
            }
            const commitId = context.payload.pull_request.head.sha;
            await github.rest.pulls.createReview({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
              commit_id: commitId,
              event: 'COMMENT',
              comments
            });