name: PR Code Review Bot (Inline Comments)

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  review:
    if: github.repository == '2Jaeheon/escargot'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq curl

      - name: Get PR diff
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          REPO=${{ github.repository }}
          echo "Getting diff for PR #$PR_NUMBER"
          curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
               -H "Accept: application/vnd.github.v3.diff" \
               https://api.github.com/repos/$REPO/pulls/$PR_NUMBER > pr.diff
          echo "=== DIFF START ==="
          cat pr.diff
          echo "=== DIFF END ==="

      - name: Send diff to local review bot
        run: |
          REVIEW=$(jq -Rs '{diff: .}' pr.diff | \
            curl -s "${{ secrets.LOCAL_REVIEW_URL }}/review" \
              -H "Content-Type: application/json" \
              -d @-)
          echo "$REVIEW" > review.json
          echo "=== REVIEW JSON ==="
          cat review.json

      - name: Post inline review comments
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          REPO=${{ github.repository }}

          COMMENTS=$(cat review.json | jq -c .)
          if [ "$COMMENTS" = "[]" ] || [ -z "$COMMENTS" ]; then
            echo "No inline comments to post."
            exit 0
          fi

          # GitHub Review API
          curl -s -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d "{
              \"body\": \"Automated review by LLM\",
              \"event\": \"COMMENT\",
              \"comments\": $COMMENTS
            }" \
            https://api.github.com/repos/$REPO/pulls/$PR_NUMBER/reviews